function varargout=readsac(filename,plotornot,osd)
% [SeisData,HdrData,tnu,pobj,tims]=READSAC(filename)
% [SeisData,HdrData,tnu,pobj,tims]=READSAC(filename,1)
% [SeisData,HdrData,tnu,pobj,tims]=READSAC(filename,1,'l')
% [SeisData,HdrData,tnu,pobj,tims]=READSAC(filename,1,'b')
%
% READSAC(...)
%
% Reads SAC-formatted data (and makes a plot)
%
% INPUT:
%
% filename        The filename, full path included
% plotornot       1 Makes a plot
%                 0 Does not make a plot
% osd             'b' for data saved on Solaris read into Linux
%                 'l' for data saved on Linux read into Linux
%
% OUPUT:
%
% SeisData        The number vector
% HdrData         The header structure array
% tnu             The handle to the plot title; or appropriate string
% pobj            The handle to the plot line and the xlabel
% tims            The times on the x-axis
%
% Last modified by fjsimons-at-alum.mit.edu, 15.11.2004

defval('plotornot',0)
defval('osd',osdep)

%osd='b'

fid=fopen(filename,'r',osd);
if fid==-1
  error([ 'File ',filename,' does not exist in current path ',pwd])
end
HdrF=fread(fid,70,'float32');
HdrN=fread(fid,15,'int32');
HdrI=fread(fid,20,'int32');
HdrL=fread(fid,5,'int32');
HdrK=str2mat(fread(fid,[8 24],'char'))';
SeisData=fread(fid,HdrN(10),'float32');
fclose(fid);

HdrData=struct(...
  'NPTS',HdrN(10),...
  'B',HdrF(6),...
  'E',HdrF(7),...
  'T0',HdrF(11),...
  'T1',HdrF(12),...
  'DELTA',HdrF(1),...
  'SCALE',HdrF(4),...
  'STLA',HdrF(32),...    
  'STLO',HdrF(33),...
  'STEL',HdrF(34),...
  'STDP',HdrF(35),...
  'EVLA',HdrF(36),...
  'EVLO',HdrF(37),...
  'EVEL',HdrF(38),...
  'EVDP',HdrF(39),...
  'MAG',HdrF(40),...
  'GCARC',HdrF(54),...
  'NZYEAR',HdrN(1),...
  'NZJDAY',HdrN(2),...
  'NZHOUR',HdrN(3),...
  'NZMIN',HdrN(4),...
  'NZSEC',HdrN(5),...
  'NZMSEC',HdrN(6),...
  'NVHDR',HdrN(7),...
  'KINST',deblank(HdrK(24,:)),...
  'KCMPNM',leadblnk(deblank(HdrK(21,:))),...
  'KSTNM',deblank(HdrK(1,:)),...
  'KUSER0',deblank(HdrK(18,:)));

tims=linspace(HdrData.B,HdrData.E,HdrData.NPTS);

if plotornot==1
  pobj=plot(tims,SeisData);
  filename(find(abs(filename)==95))='-';
  tnu=title(nounder(suf(filename,'/')));
  axis tight
  pobj(2)=xlabel([ 'Time (s)']);
else
  tnu=nounder(suf(filename,'/'));
  pobj=0;
end

nam={'SeisData' 'HdrData' 'tnu' 'pobj','tims'};
for index=1:nargout
  varargout{index}=eval(nam{index});
end
